---
################################################################################
- name: Update/Upgrade Linux
  hosts: VMs
  sudo: true
  tasks:
   - name: Updates a server
     apt: update_cache=yes
   - name: Upgrade a server
     apt: upgrade=full
################################################################################

################################################################################
- name: Install fail2ban package
  hosts: VMs
  sudo: true
  tasks:
    - name: Install fail2ban package
      apt: pkg=fail2ban state=present
    - name: Check to see if its running
      shell: /etc/init.d/fail2ban status
      register: fail2ban
    - debug: msg="{{ fail2ban.stdout }}"
################################################################################

################################################################################
- name: Setup UFW
  hosts: VMs
  sudo: true
  tasks:
    - name: Ensure ufw is at the latest version
      apt: pkg=ufw state=latest
      tags: ufw
    - name: Set ufw policy to deny all incoming connections
      ufw: policy=deny direction=incoming
      tags: ufw
    - name: Set ufw policy to allow all outgoing connections
      ufw: policy=allow direction=outgoing
      tags: ufw
    - name: Set ufw to allow ntp
      ufw: rule=allow port=ntp
      tags: ufw
    - name: Set ufw rule to limit connections on ssh/tcp (port 22)
      ufw: rule=limit port=ssh proto=tcp
      tags: ufw
    - name: Set ufw rule to limit connections on www/tcp (port 80)
      ufw: rule=limit port=www proto=tcp
      tags: ufw
    - name: Set ufw rule to limit connections on https/tcp (port 443)
      ufw: rule=limit port=https proto=tcp
      tags: ufw
    - name: Enable ufw logging
      ufw: logging=on
      tags: ufw
    - name: Start ufw
      ufw: state=enabled
      tags: ufw
################################################################################


################################################################################
- name: Install Docker
  hosts: VMs
  sudo: true
  roles:
    - angstwad.docker_ubuntu
  tasks:
    - name: Copy over nginx folder
      copy: src=../nginx/ dest=/var/nginx/ mode=0644
    - name: Copy over nodejs folder
      copy: src=../nodejs/ dest=/var/nodejs/ mode=0644

    - name: Copy over Docker Compose file
      copy: src=../docker-compose.yml dest=/var/docker-compose.yml mode=0644

    - name: Copy over Docker up.sh script file
      copy: src=../up.sh dest=/var/up.sh mode=0755
    - name: Copy over Docker down.sh script file
      copy: src=../down.sh dest=/var/down.sh mode=0755

    - name: Build & Run Docker Compose
      shell: cd /var && ./up.sh
      async: 120
      poll: 0
- name: Stop/Start DockerCompose
  hosts: VMs
  sudo: true
  tasks:
    - name: Give Docker time to build
      shell: echo 'Docker needs a couple minutes to build/run all the containers'
      register: foo
    - debug: msg="{{ foo.stdout }}"
################################################################################