---
################################################################################
- name: Update web static files for nginx
  hosts: VMs
  sudo: true
  tasks:
    - name: Sync nginx files (including the static web files)
      synchronize:
        src: ../nginx/
        dest: /var/nginx/

- name: Update the nodejs server files
  hosts: VMs
  sudo: true
  tasks:
    - name: Sync nodejs files (including the static web files)
      synchronize:
        src: ../nodejs/
        dest: /var/nodejs/
        rsync_opts:
          - "--exclude=node_modules"

- name: Stop/Start DockerCompose
  hosts: VMs
  sudo: true
  tasks:
    - name: Teardown docker
      shell: cd /var && ./down.sh      
    - name: Build docker
      shell: cd /var && ./up.sh
      async: 120
      poll: 0
- name: Stop/Start DockerCompose
  hosts: VMs
  sudo: true
  tasks:
    - name: Give Docker time to build
      shell: echo 'Docker needs a couple minutes to build/run all the containers'
      register: foo
    - debug: msg="{{ foo.stdout }}"
################################################################################